name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.1'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: npm install

    - name: Configure Git identity
      run: |
        git config  user.name "SergioToro-23" 
        git config  user.email "sergioandres.19@hotmail.com" 
        git config --list          

    - name: Build and deploy
      run: |
          ng deploy --base-href=https://SergioToro-23.github.io/Leidy-mi-amorcito/ --no-silent
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
